"""taula email_log

Revision ID: 51fe62135e38
Revises: ecb9305eacd0
Create Date: 2026-03-27 14:35:10.301725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51fe62135e38'
down_revision = 'ecb9305eacd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analisi_id', sa.Integer(), nullable=False),
    sa.Column('tipus_slug', sa.String(length=50), nullable=False),
    sa.Column('destinatari', sa.String(length=200), nullable=False),
    sa.Column('assumpte', sa.String(length=300), nullable=False),
    sa.Column('enviat_per', sa.String(length=120), nullable=False),
    sa.Column('enviat_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analisi_id'], ['analisi.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_log_analisi_id'), ['analisi_id'], unique=False)

    # NOTE: keeping existing analisi indexes (dades_data, dades_gin, tipus_data)
    # They exist in the DB but not in the model — do NOT drop them.

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_from_name')
        batch_op.drop_column('email_from_address')
        batch_op.drop_column('email_smtp_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_smtp_password', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email_from_address', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email_from_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    with op.batch_alter_table('email_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_log_analisi_id'))

    op.drop_table('email_log')
    # ### end Alembic commands ###
