"""Taula edit_lock

Revision ID: 5c91ed62e267
Revises: b8b0e4415d32
Create Date: 2026-03-19 16:48:13.600784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c91ed62e267'
down_revision = 'b8b0e4415d32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edit_lock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analisi_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=120), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analisi_id'], ['analisi.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('edit_lock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_edit_lock_analisi_id'), ['analisi_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edit_lock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_edit_lock_analisi_id'))

    op.drop_table('edit_lock')
    # ### end Alembic commands ###
