"""Schema inicial amb jsonb

Revision ID: b8b0e4415d32
Revises: 
Create Date: 2026-03-19 12:42:41.700465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSONB


# revision identifiers, used by Alembic.
revision = 'b8b0e4415d32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analisi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipus', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('dades', JSONB(), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('updated_by', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analisi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analisi_tipus'), ['tipus'], unique=False)

    op.create_table('tipus_analisi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('descripcio', sa.String(length=255), nullable=True),
    sa.Column('columnes_llista', JSONB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tipus_analisi', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tipus_analisi_slug'), ['slug'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('seccio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipus_id', sa.Integer(), nullable=False),
    sa.Column('titol', sa.String(length=100), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tipus_id'], ['tipus_analisi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('camp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seccio_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('ordre', sa.Integer(), nullable=True),
    sa.Column('grup', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['seccio_id'], ['seccio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Indexs jsonb per rendiment
    op.execute("CREATE INDEX ix_analisi_dades_gin ON analisi USING gin (dades)")
    op.execute("CREATE INDEX ix_analisi_dades_data ON analisi ((dades->>'data'))")
    op.execute("CREATE INDEX ix_analisi_tipus_data ON analisi (tipus, (dades->>'data'))")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('camp')
    op.drop_table('seccio')
    op.drop_table('user')
    with op.batch_alter_table('tipus_analisi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tipus_analisi_slug'))

    op.drop_table('tipus_analisi')
    with op.batch_alter_table('analisi', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analisi_tipus'))

    op.drop_table('analisi')
    # ### end Alembic commands ###
